### PR TITLE
Add schema spy templates

### PR DESCRIPTION
**Pull request by nikola-rados**

### CODE REVIEW

**Review by WadeBarnes — COMMENTED** [review]
For bonus points you could integrate schema-spy into the jenkins build and deployment to `dev`; https://github.com/bcgov/sheriff-scheduling-configurations/blob/master/jenkins/build/Jenkinsfile.  You'll want it deployed last so it picks up any database migrations from the API deployment running.

**Comment by nikola-rados** [comment]
@WadeBarnes I've added in a stage to the `Jenkinsfile` but I have some questions. 

I was using the other `schema-spy` projects as reference but they seemed to have a slightly different approach to the jenkins config. Those projects were using the `OpenshiftDSL` plugin, but this project wasn't. Does using it here make sense even though it it not used in any of the other stages? If not, how do we set up? 

On top of that we know that we don't want to be running `schema-spy` on `PROD`. The other projects were using [build lists](https://github.com/bcgov/violation-dispute-form/blob/master/jenkins/config.groovy#L22) to determine which apps get run. This project didn't have that infrastructure but it also seemed to only mention `-dev` in the [`ENV`](https://github.com/bcgov/sheriff-scheduling-configurations/blob/master/jenkins/build/Jenkinsfile#L9) set up. I'm not sure if that means we are only running this for `DEV` and don't need to worry about separating the `PROD` apps, or if those references are just a means to get some other information. Do we need to set up something similar to the other `schema-spy` projects in terms of separating `PROD` and `DEV`?

**Comment by WadeBarnes** [comment]
@nikola-rados, In the other projects like https://github.com/bcgov/representation-grant-app, schema-spy is manually built and deployed to dev (via tagging) since the image does not change very often.  What happens in the build pipeline is the container gets recycled so it regenerates the schema if there were any changes.  Having schema-spy only in dev is sufficient for the use case.  If no changes are made the `APPS` list in `src/bc/baseConfig.groovy` then schema-spy will not make it's way to `test` or `prod`, since the deployment scripts use the `APPS` list to determine which images to tag.

It would be best to follow the project's conventions when adding support for recycling schema-spy which would require a simple `oc-recycle.sh` script that uses the `oc scale` command be added to the `./scripts` folder and the `player.sh` script to be updated to call it.  Then you can call the new `player` script command form the build pipeline.

**Review by WadeBarnes — COMMENTED** [review]
Looks good to me.

**Pull request merged**
